### ISSUE TITLE
Issue:control.py start 

### ISSUE THREAD

**Issue by arhadnane** [pomo-mondreganto/ForcAD#19]
Hi, 
Nice project, thank you.
I've some issue when i run :  ./control.py start --fast
![Error_control_start](https://user-images.githubusercontent.com/14889338/81018019-260c6e00-8e53-11ea-8ca6-3a166774fa5a.jpg)

**Comment by pomo-mondreganto** [comment]
Hi! 
It seems like the problem is with docker hub, not ForcAD itself. You can't access public docker images library for some reason. Can you try using VPN?

**Comment by arhadnane** [comment]
I am behind proxy, I've set the proxy and the problem not solved

**Comment by pomo-mondreganto** [comment]
I can try publishing the Docker image to some other repository (GitHub Packages, for instance). Please test the GitHub Packages images are accessible to you and, if so, ping me.

**Comment by arhadnane** [comment]
It's Ok . it is corporate proxy  problem. 
thank you.

**Comment by arhadnane** [comment]
I 've another error:
All of step are ok until 10 when I've error:
Step 7/17 : ADD docker_config/db_check.py /db_check.py
 ---> 535b3c9fd560
Step 8/17 : ADD docker_config/check_initialized.py /check_initialized.py
 ---> 2bbe2a6a2de0
Step 9/17 : RUN chmod +x /await_start.sh
 ---> Running in 836b057584b9
Removing intermediate container 836b057584b9
 ---> 68c9c85974b9
Step 10/17 : ADD ./checkers/requirements.txt /checker_requirements.txt
ERROR: Service 'celery' failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builder555367503/checkers/requirements.txt: no such file or directory
[-] Failed!

**Comment by pomo-mondreganto** [comment]
You haven’t created checker requirements file, as per documentation. It has to be placed at `checkers/requirements.txt`.
