### ISSUE TITLE
Flag is invalid or too old

### ISSUE THREAD

**Issue by arhadnane** [pomo-mondreganto/ForcAD#20]
Hi,
Thank you for your great work.
I've put all of project like described in your documents, I 've a DestructiveFarm and CTF project, all of them are well configured and run well, but I've in Destructive Farm a message that flag rejected and like message: Flag is invalid or too old.
I look  to all python codes's in all projects, but I can't figure out where are the problem. 
I will be glad if I can run this project in local host.(127.0.0.1)
Thank you.

**Comment by pomo-mondreganto** [comment]
Hi!

All flags have their "lifetime" -- a number of rounds (after it's added to a service) a flag can be submitted to a jury system. The error message you get most likely indicates that the flag you're trying to submit has reached the end of its lifetime.

More about lifetime can be read in README of the project in the "configuration" section.

**Comment by arhadnane** [comment]
Hi,
But, i lunch all system in the same times
And the table flags is empty.

**Comment by pomo-mondreganto** [comment]
Do the PUT actions finish successfully? Can you attach the `teamtaskslog` table contents or/and `celery` container logs?

**Comment by arhadnane** [comment]
![teamtasklog](https://user-images.githubusercontent.com/14889338/81402845-b41d7880-9121-11ea-8b29-eaad4baaadea.jpg)

**Comment by pomo-mondreganto** [comment]
Well, it seems like you've deleted the checker file.

**Comment by arhadnane** [comment]
No i don't touch any thing,

**Comment by arhadnane** [comment]
How to  add files to checker ?

**Comment by pomo-mondreganto** [comment]
1. Are you starting ForcAD with docker-compose as per README, from the master branch?

2. DestructiveFarm is a team flag farm, i.e. each team starts it's own DF instance to submit flags from their sploits, with their team's token.

**Comment by arhadnane** [comment]
1- I started with docker-compose like described in README in localhost machine.
2-How can i add token by team?  There is not a lot of documents about this topic, we need a detailed explanation.

**Comment by pomo-mondreganto** [comment]
As for DF issue -- each token has format `TEAMNAME:TOKEN`. You should pass the value of `TOKEN` to the config to submit flags for team `TEAMNAME`.

**Comment by pomo-mondreganto** [comment]
As for the checker problem -- I think I know the issue now. Are you trying to start the testing setup?

**Comment by arhadnane** [comment]
![Capture1](https://user-images.githubusercontent.com/14889338/81416817-ca373300-9139-11ea-8ae9-8165f438d6bf.JPG)
![Capture2](https://user-images.githubusercontent.com/14889338/81416827-cf947d80-9139-11ea-8f08-d8123e67bb33.JPG)

**Comment by arhadnane** [comment]
this the result of $./control start
root@kali:~/ForcAD# ./control.py start 
Removing forcad_nginx_1
Building celery
Step 1/17 : FROM python:3.7
 ---> 84d66a048f90
Step 2/17 : ENV PYTHONUNBUFFERED=1
 ---> Using cache
 ---> cb2475838444
Step 3/17 : RUN apt-get update && apt-get install -y libpq-dev
 ---> Using cache
 ---> bfe80df3c9d0
Step 4/17 : ADD backend/requirements.txt /requirements.txt
 ---> Using cache
 ---> fa15e98bda45
Step 5/17 : RUN pip install -r /requirements.txt
 ---> Using cache
 ---> 0cc3f4bfc054
Step 6/17 : ADD docker_config/await_start.sh /await_start.sh
 ---> Using cache
 ---> 282b786b7993
Step 7/17 : ADD docker_config/db_check.py /db_check.py
 ---> Using cache
 ---> 7f260e2602af
Step 8/17 : ADD docker_config/check_initialized.py /check_initialized.py
 ---> Using cache
 ---> 9b730b3ec095
Step 9/17 : RUN chmod +x /await_start.sh
 ---> Using cache
 ---> 80a9f574f289
Step 10/17 : ADD ./checkers/requirements.txt /checker_requirements.txt
 ---> Using cache
 ---> 3eed49c726e8
Step 11/17 : RUN pip install -r /checker_requirements.txt
 ---> Using cache
 ---> 966c7b4e61b5
Step 12/17 : ADD ./checkers /checkers
 ---> Using cache
 ---> e877f5cb4c65
Step 13/17 : ADD backend /app
 ---> Using cache
 ---> 067c8f96cdb6
Step 14/17 : ADD ./docker_config/celery/entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> dd45eb870b82
Step 15/17 : RUN chmod +x /entrypoint.sh
 ---> Using cache
 ---> 0eb564cbb80f
Step 16/17 : USER nobody
 ---> Using cache
 ---> 450a4ae36abf
Step 17/17 : CMD ["/entrypoint.sh"]
 ---> Using cache
 ---> 0bff03d86e25

Successfully built 0bff03d86e25
Successfully tagged forcad_celery:latest
Building celerybeat
Step 1/17 : FROM python:3.7
 ---> 84d66a048f90
Step 2/17 : ENV PYTHONUNBUFFERED=1
 ---> Using cache
 ---> cb2475838444
Step 3/17 : RUN apt-get update && apt-get install -y libpq-dev
 ---> Using cache
 ---> bfe80df3c9d0
Step 4/17 : ADD backend/requirements.txt /requirements.txt
 ---> Using cache
 ---> fa15e98bda45
Step 5/17 : RUN pip install -r /requirements.txt
 ---> Using cache
 ---> 0cc3f4bfc054
Step 6/17 : ADD docker_config/await_start.sh /await_start.sh
 ---> Using cache
 ---> 282b786b7993
Step 7/17 : ADD docker_config/db_check.py /db_check.py
 ---> Using cache
 ---> 7f260e2602af
Step 8/17 : ADD docker_config/check_initialized.py /check_initialized.py
 ---> Using cache
 ---> 9b730b3ec095
Step 9/17 : RUN chmod +x /await_start.sh
 ---> Using cache
 ---> 80a9f574f289
Step 10/17 : ADD ./checkers/requirements.txt /checker_requirements.txt
 ---> Using cache
 ---> 3eed49c726e8
Step 11/17 : RUN pip install -r /checker_requirements.txt
 ---> Using cache
 ---> 966c7b4e61b5
Step 12/17 : ADD ./checkers /checkers
 ---> Using cache
 ---> e877f5cb4c65
Step 13/17 : ADD backend /app
 ---> Using cache
 ---> 067c8f96cdb6
Step 14/17 : ADD ./docker_config/celery/entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> dd45eb870b82
Step 15/17 : RUN chmod +x /entrypoint.sh
 ---> Using cache
 ---> 0eb564cbb80f
Step 16/17 : USER nobody
 ---> Using cache
 ---> 450a4ae36abf
Step 17/17 : CMD ["/entrypoint.sh"]
 ---> Using cache
 ---> 0bff03d86e25

Successfully built 0bff03d86e25
Successfully tagged forcad_celerybeat:latest
Building flower
Step 1/17 : FROM python:3.7
 ---> 84d66a048f90
Step 2/17 : ENV PYTHONUNBUFFERED=1
 ---> Using cache
 ---> cb2475838444
Step 3/17 : RUN apt-get update && apt-get install -y libpq-dev
 ---> Using cache
 ---> bfe80df3c9d0
Step 4/17 : ADD backend/requirements.txt /requirements.txt
 ---> Using cache
 ---> fa15e98bda45
Step 5/17 : RUN pip install -r /requirements.txt
 ---> Using cache
 ---> 0cc3f4bfc054
Step 6/17 : ADD docker_config/await_start.sh /await_start.sh
 ---> Using cache
 ---> 282b786b7993
Step 7/17 : ADD docker_config/db_check.py /db_check.py
 ---> Using cache
 ---> 7f260e2602af
Step 8/17 : ADD docker_config/check_initialized.py /check_initialized.py
 ---> Using cache
 ---> 9b730b3ec095
Step 9/17 : RUN chmod +x /await_start.sh
 ---> Using cache
 ---> 80a9f574f289
Step 10/17 : ADD ./checkers/requirements.txt /checker_requirements.txt
 ---> Using cache
 ---> 3eed49c726e8
Step 11/17 : RUN pip install -r /checker_requirements.txt
 ---> Using cache
 ---> 966c7b4e61b5
Step 12/17 : ADD ./checkers /checkers
 ---> Using cache
 ---> e877f5cb4c65
Step 13/17 : ADD backend /app
 ---> Using cache
 ---> 067c8f96cdb6
Step 14/17 : ADD ./docker_config/celery/entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> dd45eb870b82
Step 15/17 : RUN chmod +x /entrypoint.sh
 ---> Using cache
 ---> 0eb564cbb80f
Step 16/17 : USER nobody
 ---> Using cache
 ---> 450a4ae36abf
Step 17/17 : CMD ["/entrypoint.sh"]
 ---> Using cache
 ---> 0bff03d86e25

Successfully built 0bff03d86e25
Successfully tagged forcad_flower:latest
Building initializer
Step 1/13 : FROM python:3.7
 ---> 84d66a048f90
Step 2/13 : ENV PYTHONUNBUFFERED=1
 ---> Using cache
 ---> cb2475838444
Step 3/13 : RUN apt-get update && apt-get install -y libpq-dev
 ---> Using cache
 ---> bfe80df3c9d0
Step 4/13 : ADD backend/requirements.txt /requirements.txt
 ---> Using cache
 ---> fa15e98bda45
Step 5/13 : RUN pip install -r /requirements.txt
 ---> Using cache
 ---> 0cc3f4bfc054
Step 6/13 : ADD docker_config/await_start.sh /await_start.sh
 ---> Using cache
 ---> 282b786b7993
Step 7/13 : ADD docker_config/db_check.py /db_check.py
 ---> Using cache
 ---> 7f260e2602af
Step 8/13 : ADD docker_config/check_initialized.py /check_initialized.py
 ---> Using cache
 ---> 9b730b3ec095
Step 9/13 : RUN chmod +x /await_start.sh
 ---> Using cache
 ---> 80a9f574f289
Step 10/13 : ADD backend /app
 ---> Using cache
 ---> 15d289ffdc38
Step 11/13 : ADD ./docker_config/initializer/entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> fafb54bf803f
Step 12/13 : RUN chmod +x /entrypoint.sh
 ---> Using cache
 ---> 99833eaa5afc
Step 13/13 : CMD ["/entrypoint.sh"]
 ---> Using cache
 ---> 79a6e72facc9

Successfully built 79a6e72facc9
Successfully tagged forcad_initializer:latest
Building webapi
Step 1/13 : FROM python:3.7
 ---> 84d66a048f90
Step 2/13 : ENV PYTHONUNBUFFERED=1
 ---> Using cache
 ---> cb2475838444
Step 3/13 : RUN apt-get update && apt-get install -y libpq-dev
 ---> Using cache
 ---> bfe80df3c9d0
Step 4/13 : ADD backend/requirements.txt /requirements.txt
 ---> Using cache
 ---> fa15e98bda45
Step 5/13 : RUN pip install -r /requirements.txt
 ---> Using cache
 ---> 0cc3f4bfc054
Step 6/13 : ADD docker_config/await_start.sh /await_start.sh
 ---> Using cache
 ---> 282b786b7993
Step 7/13 : ADD docker_config/db_check.py /db_check.py
 ---> Using cache
 ---> 7f260e2602af
Step 8/13 : ADD docker_config/check_initialized.py /check_initialized.py
 ---> Using cache
 ---> 9b730b3ec095
Step 9/13 : RUN chmod +x /await_start.sh
 ---> Using cache
 ---> 80a9f574f289
Step 10/13 : ADD backend /app
 ---> Using cache
 ---> 15d289ffdc38
Step 11/13 : ADD ./docker_config/webapi/entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> d5b455558e14
Step 12/13 : RUN chmod +x /entrypoint.sh
 ---> Using cache
 ---> 7542efc2585c
Step 13/13 : CMD ["/entrypoint.sh"]
 ---> Using cache
 ---> a50c2f4f63f0

Successfully built a50c2f4f63f0
Successfully tagged forcad_webapi:latest
Building gevent_flag_submitter
Step 1/13 : FROM python:3.7
 ---> 84d66a048f90
Step 2/13 : ENV PYTHONUNBUFFERED=1
 ---> Using cache
 ---> cb2475838444
Step 3/13 : RUN apt-get update && apt-get install -y libpq-dev
 ---> Using cache
 ---> bfe80df3c9d0
Step 4/13 : ADD backend/requirements.txt /requirements.txt
 ---> Using cache
 ---> fa15e98bda45
Step 5/13 : RUN pip install -r /requirements.txt
 ---> Using cache
 ---> 0cc3f4bfc054
Step 6/13 : ADD docker_config/await_start.sh /await_start.sh
 ---> Using cache
 ---> 282b786b7993
Step 7/13 : ADD docker_config/db_check.py /db_check.py
 ---> Using cache
 ---> 7f260e2602af
Step 8/13 : ADD docker_config/check_initialized.py /check_initialized.py
 ---> Using cache
 ---> 9b730b3ec095
Step 9/13 : RUN chmod +x /await_start.sh
 ---> Using cache
 ---> 80a9f574f289
Step 10/13 : ADD backend /app
 ---> Using cache
 ---> 15d289ffdc38
Step 11/13 : ADD ./docker_config/gevent_flag_submitter/entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> 571bf99ec521
Step 12/13 : RUN chmod +x /entrypoint.sh
 ---> Using cache
 ---> d360a4a4f5ce
Step 13/13 : CMD ["/entrypoint.sh"]
 ---> Using cache
 ---> e740245df1ac

Successfully built e740245df1ac
Successfully tagged forcad_gevent_flag_submitter:latest
Building nginx
Step 1/5 : FROM nginx:1.15.9-alpine
 ---> 32a037976344
Step 2/5 : ADD ./docker_config/nginx/conf/ /etc/nginx/conf.d/
 ---> Using cache
 ---> 06d52cc24083
Step 3/5 : ADD ./docker_config/nginx/proxy_params /etc/nginx/proxy_params
 ---> Using cache
 ---> b607ca310fa2
Step 4/5 : ADD ./front/dist /var/www/front
 ---> Using cache
 ---> eff9c843f8c9
Step 5/5 : CMD ["nginx", "-g", "daemon off;"]
 ---> Using cache
 ---> 2c75f450621a

Successfully built 2c75f450621a
Successfully tagged forcad_nginx:latest
Building postgres
Step 1/6 : FROM postgres:12.1
 ---> cf879a45faaa
Step 2/6 : RUN apt-get update && apt-get install -y gcc make postgresql-server-dev-12
 ---> Using cache
 ---> 875d98b0cacb
Step 3/6 : ADD backend/fast_rs /rs
 ---> Using cache
 ---> 992ccb94c109
Step 4/6 : WORKDIR /rs
 ---> Using cache
 ---> 75468d0ea04d
Step 5/6 : RUN make
 ---> Using cache
 ---> 9dbc5ee14145
Step 6/6 : WORKDIR /
 ---> Using cache
 ---> e863501f2f88

Successfully built e863501f2f88
Successfully tagged forcad_postgres:latest
Starting forcad_initializer_1 ... 
forcad_webapi_1 is up-to-date
forcad_celerybeat_1 is up-to-date
forcad_celery_1 is up-to-date
forcad_rabbitmq_1 is up-to-date
forcad_gevent_flag_submitter_1 is up-to-date
Recreating 41bd7c3a0c01_forcad_nginx_1 ... 
forcad_redis_1 is up-to-date
Starting forcad_initializer_1          ... done
Recreating 41bd7c3a0c01_forcad_nginx_1 ... done
root@kali:~/ForcAD# ./control.py print_tokens
team 1:4bf2926be6ae6662
team 2:805c7ec5dab4331e

**Comment by arhadnane** [comment]
this is a part from config of DestructiveFarm:
We have only one key: "TEAM_TOKEN" , we can not add more than one token.
'SYSTEM_PROTOCOL': 'forcad_tcp',
      'SYSTEM_HOST': '127.0.0.1',
      'SYSTEM_PORT': 31337,
      'TEAM_TOKEN': '4bf2926be6ae6662',

**Comment by arhadnane** [comment]
![DestructiveFarm](https://user-images.githubusercontent.com/14889338/81418654-8560cb80-913c-11ea-93b3-51459a3bdcbd.JPG)
![ForcAD](https://user-images.githubusercontent.com/14889338/81418663-8d207000-913c-11ea-8965-b96721009eca.JPG)

**Comment by arhadnane** [comment]
Some log from redis:
dump flags
$-1
dump flag
$-1
dump teams
$204
�@[@a{"id": 2, "name 
"team 2" ip@127.0 `token@806aba47ace40d28@/highl te@Sfalse}�@[@a{"id": 1, "name 
"team 1" ip@127.0 `token@644c25ad0da41424@/highl te@Sfalse}	=4s3m�\t
dump team
$-1
exist flags
-ERR unknown command `exist`, with args beginning with: `flags`, 
exists teams
:1
exists flags
:0
exists flag
:0

**Comment by pomo-mondreganto** [comment]
To start the test service setup, please, run the following commands (or take them from `.travis.yml`:

```bash
export TEST=1
export TEST_TYPE=classic
python tests/setup_forcad.py
./control.py setup 
export $(find . -name "environment.env" -exec egrep -v '^#' {} \; | xargs)
./control.py start
```

**Comment by arhadnane** [comment]
not working, same error

**Comment by pomo-mondreganto** [comment]
It runs on travis like that...

**Comment by arhadnane** [comment]
![errorTest](https://user-images.githubusercontent.com/14889338/81436760-89e7ad00-9159-11ea-89da-5e53ccfb7b29.JPG)

**Comment by arhadnane** [comment]
python3 checker.py check 127.0.0.1
Check failed
Error on http://127.0.0.1:5001/ping/: 404

**Comment by arhadnane** [comment]
![teamtasklog](https://user-images.githubusercontent.com/14889338/81439063-5018a580-915d-11ea-8f97-cc9b4b82c56a.jpg)

**Comment by arhadnane** [comment]
![teamtasks](https://user-images.githubusercontent.com/14889338/81439103-6161b200-915d-11ea-844c-f11a56cd0134.JPG)

**Comment by arhadnane** [comment]
the problem is located in this function below, why :
def get_flag_by_field(field_name: str, field_value, round: int) -> helplib.models.Flag:
    """Get flag by generic field
        :param field_name: field name to ask cache for
        :param field_value: value of the field "field_name" to filter on
        :param round: current round
        :return: Flag model instance with flag.field_name == field_value
        :raises: FlagSubmitException if nothing found
    """
    with storage.get_redis_storage().pipeline(transaction=True) as pipeline:
        cached, = pipeline.exists('flags:cached').execute()
        if not cached:
            cache_helper(
                pipeline=pipeline,
                cache_key='flags:cached',
                cache_func=caching.cache_last_flags,
                cache_args=(round, pipeline),
            )
        pipeline.exists(f'flag:{field_name}:{field_value}')
        pipeline.get(f'flag:{field_name}:{field_value}')
        flag_exists, flag_json = pipeline.execute()
    if not flag_exists:
        raise helplib.exceptions.FlagSubmitException('Flag is invalid or too old')
    flag = helplib.models.Flag.from_json(flag_json)
    return flag

**Comment by pomo-mondreganto** [comment]
Hi!

Sorry for the long wait, but I've just merged a major update to ForcAD. To test it yourself, please, run this command **in the same terminal**:

```bash
git clone https://github.com/pomo-mondreganto/ForcAD
cd ForcAD
python3 -m pip install control_requirements.txt
export TEST=1
export TEST_TYPE=classic
python3 tests/setup_forcad.py
./control.py setup 
export $(find . -name "environment.env" -exec egrep -v '^#' {} \; | xargs)
./control.py start
```

Judging by the lest screenshots you attached, the issue with checkers is resolved, but the test service is behaving on the first 2 teams. If the same issue persists on a new ForcAD version, attach the following data:

1. Logs of `celery` container: 

```bash
docker-compose logs -f celery
```

2. Teams table:

```sql
select * from teams;
```

3. Tasks table:

```sql
select * from tasks;
```

4. `teamtaskslog` table:

```sql
select * from teamtaskslog order by ts desc;
```

And your configuration file (`backend/config/config.yml`).

**Comment by arhadnane** [comment]
Hi;
sorry for the delay in responding; because of coronavirus and the holidays.
It's ok, it's working, thank you very much.

**Comment by pomo-mondreganto** [comment]
Glad I could help!
