### ISSUE TITLE
Round progress calculation is wrong (?)

### ISSUE THREAD

**Issue by ldruschk** [pomo-mondreganto/ForcAD#23]
See https://github.com/pomo-mondreganto/ForcAD/blob/4190b57dc784b0289cef0b66e1649004ccc37ada/front/src/views/Scoreboard.vue#L78

```
this.roundProgress =
    (new Date().getTime() / 1000 -
        this.roundStart -
        this.roundTime) /
    this.roundTime;
```

I haven't looked into the complete code yet, but I believe `this.roundTime` shouldn't be subtracted from the rest. This way you always have negative values unless the end of the round is reached in which case the progress would be 0 but never more than 0.

**Comment by xmikasax** [comment]
It is an expected behaviour for classic mode as we receive an update message from the previous round, so one round time must be subtracted. You are right that it is not the case for blitz mode. We will fix this in future updates.

**Comment by ldruschk** [comment]
After giving this some more thought I think this was a misunderstanding on my part. Assuming that the round being displayed is the past round and not the current round, the end of the round being displayed is the start time of the round for which we want to calculate the progress
