### ISSUE TITLE
Unable to start ForcAD without creating undocumented files

### ISSUE THREAD

**Issue by kolayne** [pomo-mondreganto/ForcAD#33]
I was expecting to be able to start a minimal working instance of ForcAD by just running `docker-compose up`, however, I'm getting the `ERROR: Couldn't find env file: /home/nikolay/Docs/ctf/fffad/docker_config/postgres/environment.env` message (and other similar messages after I create a file from the previous one). I don't see any documentation about it (neither in README.md nor in... nowhere, actually, because there are no other docs, are they?) nor an example config. I think this should be explained or **at least mentioned** in the docs because I don't even know whether I've done something wrong (have a wrong version of `docker`/`docker-compose`? checked out a wrong branch? live on a wrong planet?) or these errors should occur and I should manually create the config files based on errors I'm getting from the containers after I create all the env files.

Btw, I am also getting some errors from containers, for which I was not forced to create an env file by docker. I didn't yet dig into it, but at the moment I don't understand how I can pass environment variables to, for example, `initializer` (`db_checker.py`).

Here there are some details about my machine (however, I don't think any of these are related to the problems above):
- OS: Linux Mint 20 Cinnamon (based on Ubuntu 20.04)
- `Docker version 19.03.13, build 4484c46d9d`
- `docker-compose version 1.25.0, build unknown`
- ForcAD's `HEAD` is at `master`, `ae0da63`

**Comment by pomo-mondreganto** [comment]
Hi! 

These files are created by `./control.py setup` command, as documented in step 4 of "Running" section.

**Comment by kolayne** [comment]
Oops, I'm so sorry... :cry:
No idea, what has happened to me and why I stopped reading the Running section before it ended. Thank you!
