### ISSUE TITLE
Generated page is empty

### ISSUE THREAD

**Issue by NickkNike** [pomo-mondreganto/ForcAD#59]
After running on your's guide all services are up and visible in the list of Dockers, but HTML page on 127.0.0.1:8080 is empty, but named ForcAD

**Comment by pomo-mondreganto** [comment]
Hi! 

Can you please elaborate on the issue? 

* Which version are you using? It's recommended to use the latest release from [Releases](https://github.com/pomo-mondreganto/ForcAD/releases) page.
* Can you provide the browser console logs (as the title loaded, there's most likely some frontend-error, and the browser console should show them)?
