### ISSUE TITLE
No such file 'docker-compose'

### ISSUE THREAD

**Issue by ymgh96** [pomo-mondreganto/ForcAD#63]
After I running this command without error:"./control.py setup"
I get the bellow error when I run this command:"./control.py start --fast" on version 1.2.1
No such file or directory: 'docker-compose'
What I should to do?
```
root@kali:~/ForcAD_v1.2.1# ls
backend     docker-compose-base.yml  docker_config  README.md
checkers    docker-compose-fast.yml  front          requirements.txt
control.py  docker-compose.yml       LICENSE
```

**Comment by pomo-mondreganto** [comment]
Hi!

You need to have Docker (https://docs.docker.com/get-docker/) and Docker Compose (https://docs.docker.com/compose/install/) installed.

**Comment by ymgh96** [comment]
your point solves my problem. Thank you so much. I'm sorry for my inexperience🙈
