### ISSUE TITLE
Support for docker compose plugin?

### ISSUE THREAD

**Issue by spagnoloG** [pomo-mondreganto/ForcAD#75]
https://github.com/pomo-mondreganto/ForcAD/blob/c5341a0691f46cc8f906b751d10766466a7bfff7/cli/utils.py#L138

Docker recently migrated to docker compose plugin, so maybe support for it would be nice ( `docker compose` and not `docker-compose`). Support of both options would be even nicer :)

**Comment by pomo-mondreganto** [comment]
Nice idea, will do
